apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  labels:
    app: notifier
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: notifier:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_URL
              value: redis://$(REDIS_SVC_NAME):6379/1
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
  labels:
    app: notifier
    control-plane: controller-manager
spec:
  selector:
    app: notifier
  ports:
    - name: http
      port: 8080
    - name: https
      port: 8081
  type: ClusterIP
