apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      app: redis 
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    control-plane: controller-manager
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: NodePort
