# permissions for end users to view notificationtriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationtrigger-viewer-role
rules:
- apiGroups:
  - alarm.tmax.io
  resources:
  - notificationtriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alarm.tmax.io
  resources:
  - notificationtriggers/status
  verbs:
  - get
