# permissions for end users to edit notifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notification-editor-role
rules:
- apiGroups:
  - tmax.io.my.domain
  resources:
  - notifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io.my.domain
  resources:
  - notifications/status
  verbs:
  - get
