# permissions for end users to view notifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notification-viewer-role
rules:
- apiGroups:
  - alarm.tmax.io
  resources:
  - notifications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alarm.tmax.io
  resources:
  - notifications/status
  verbs:
  - get
