# permissions for end users to edit notificationtriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notificationtrigger-editor-role
rules:
- apiGroups:
  - alarm.tmax.io
  resources:
  - notificationtriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alarm.tmax.io
  resources:
  - notificationtriggers/status
  verbs:
  - get
