# permissions for end users to edit smtpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smtpconfig-editor-role
rules:
- apiGroups:
  - alarm.tmax.io
  resources:
  - smtpconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alarm.tmax.io
  resources:
  - smtpconfigs/status
  verbs:
  - get
