# permissions for end users to view smtpconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smtpconfig-viewer-role
rules:
- apiGroups:
  - alarm.tmax.io
  resources:
  - smtpconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alarm.tmax.io
  resources:
  - smtpconfigs/status
  verbs:
  - get
