apiVersion: tmax.io.my.domain/v1alpha1
kind: Notification
metadata:
  name: email-notification-sample
spec:
  # Add fields here
  email:
    smtpcfg: smtpconfig-sample
    from: taejune_ahn@tmax.co.kr
    to: taejune_ahn@tmax.co.kr
    subject: "[Notification] email-notification-sample"
    body: "Hello"
